[tool.kedro]
package_name = "prediccion_preparacion_pandemias"
project_name = "Prediccion Preparacion Pandemias"
kedro_init_version = "0.18.14"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/prediccion_preparacion_pandemias -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.kedro_telemetry]
project_id = "6452896051964893987014bd2029fbdb"
